[github_app]
pr_commands = [
    "/agentic_describe",
    "/agentic_review"
]

[review_agent] 
# "both" mode is too noisy, keep in "summary" mode in this repo
comments_location_policy = "both" 

# severity threshold rank for inline comments: 
# 3=action_required, 
# 2=remediation_recommended, 
# 1=informational. 
# Only findings with rank >= threshold will be published inline
inline_comments_severity_threshold = 2

# Extra prompt for usecase to be added as instruction for the agent 
issues_user_guidelines = ""
compliance_user_guidelines = ""
